swagger: '2.0'
info:
  description: 파일 바이너리 등록/제공 및 대한민국 운전면허증 이미지상의 데이터 추출(OCR기반 문자 인식) 기능을 제공함. 기존 nodejs 버전을 코틀린으로 포팅함.
  version: 1.1.0
  title: Upload-service
basePath: /upload-service/v1
tags:
  - name: image
    description: 파일 등록 관련 기능 제공
  - name: licence
    description: 운전면허증(국내) 이미지 등록 및 OCR 기반 정보 추출 기능 제공
schemes:
  - https
  - http
paths:
  /onetime/key:
    get:
      tags:
        - image
      summary: 이미지 다운로드를 위한 OTK(One time Key) 발급.
      description: '이미지 다운로드를 위한 (One time Key) 발급. 해당 키는 발급 시간 기준 지정된 duration이 경과되면 무효화 된다.'
      operationId: /onetime/key
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          type: string
          name: 'key'
          description: Key 유효시간(SEC).
          required: true
      responses:
        200:
          description: '키 발급 성공'
          schema:
            $ref: '#/definitions/onetimekey_result'
        500:
          description: 키를 발급 받는 중 오류 발생
  /file/{fileid}:
    get:
      tags:
        - image
      summary: 등록된 이미지 파일명 조회
      description: '등록된 이미지의 파일명을 조회한다.'
      operationId: /file/{fileid}
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          type: string
          name: 'fileid'
          description: 파일 아이디
          required: true
        - in: query
          type: string
          name: 'key'
          description: 발급 받은 OTK
          required: true
      responses:
        200:
          description: '조회 성공'
          schema:
            $ref: '#/definitions/filename_result'
        400:
          description: '해당 아이디의 파일이 존재하지 않거나 키가 만료된 경우'
        500:
          description: '파일명을 조회하는 중 내부 오류 발생'
  /image/{imageid}:
    get:
      tags:
        - image
      summary: 등록된 이미지 조회
      description: '등록된 이미지를 조회한다. 기타 파일인 경우 다운로드를 수행한다'
      operationId: /image/{imageid}
      parameters:
        - in: path
          type: string
          name: 'imageid'
          description: 파일 아이디
          required: true
        - in: query
          type: string
          name: 'key'
          description: 발급 받은 OTK
          required: true
      responses:
        200:
          description: '조회 성공(파일 다운로드 수행)'
          schema:
            $ref: '#/definitions/filename_result'
        400:
          description: '해당 아이디의 파일이 존재하지 않거나 키가 만료된 경우'
          schema:
            $ref: '#/definitions/filename_result_400'
        500:
          description: '파일명을 조회하는 중 내부 오류 발생'
  /upload:
    post:
      tags:
        - image
      summary: 파일 등록
      description: '등록된 이미지를 조회한다. 기타 파일인 경우 다운로드를 수행한다'
      operationId: /upload
      consumes:
        - multipart/form-data
      produces:
        - multipart/form-data
      parameters:
        - in: formData
          type: file
          name: 'files'
          description: 등록할 파일(이미지), Multipart form내의 키값은 files.
          required: true
      responses:
        200:
          description: '이미지 업로드 후 이미지 ID 를 Array 로 리턴한다.'
          schema:
            $ref: '#/definitions/fileupload_result'
        500:
          description: '파일명을 조회하는 중 내부 오류 발생'
  /licence/photo:
    post:
      tags:
        - licence
      summary: 면허증 이미지 등록 및 면허번호등의 문자열 추출
      description: '면허증 이미지 등록 및 면허증 이미지 내에서 면허번호/지역/생년월일/발급일자 등을 추출한다. 추출이 완료되면 주민등록번호 뒷자리를 마스킹하고 넓이 256px로 리사이징 하여 저장한다.'
      operationId: /licence/photo
      consumes:
        - multipart/form-data
      produces:
        - multipart/form-data
      parameters:
        - in: formData
          type: file
          name: 'file'
          description: 등록할 면허증 이미지 파일, Multipart form내의 키값은 file.
          required: true
      responses:
        200:
          description: '이미지 업로드 후 분석결과를  리턴한다.'
          schema:
            $ref: '#/definitions/licence_photo_result'
        500:
          description: '파일명을 조회하는 중 내부 오류 발생 (이미지내의 생년월일 인식 실패 포함)'
          schema:
            $ref: '#/definitions/licence_photo_result_500'
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
security:
  - ApiKeyAuth: []
definitions:
  onetimekey_result:
    properties:
      code:
        type: integer
        description: 응답코드
      result:
        type: string
        description: 발급된 OTK
      message:
        type: string
        description: 추가 메시지
    example:
      code: '200'
      message: ''
      result: 'qzpO0V1cwYjXU0P98825pJq4fLCHaZEQ'
  filename_result:
    properties:
      code:
        type: integer
        description: 응답코드
      result:
        type: string
        description: 등록된 파일의 실제 파일명
        example: 'reservation2021-01 driving distance.csv'
      message:
        type: string
        description: 추가 메시지
    example:
      code: '200'
      result: 'reservation2021-01 driving distance.csv'
      message: ''
  filename_result_400:
    properties:
      code:
        type: integer
        description: 응답코드
      result:
        type: string
        description: 등록된 파일의 실제 파일명
        example: 'reservation2021-01 driving distance.csv'
      message:
        type: string
        description: 추가 메시지
    example:
      code: '400'
      result: 'Key was expired. oneTimeKey: 1YYzEJS9RsXdmbwV8GErES1n3nPuy2JL1'
      message: ''
  fileupload_result:
    properties:
      code:
        type: integer
        description: 응답코드
      result:
        type: string
        description: 등록된 파일의 아이디
        example: 'PVnT8fC73qOZuvVi'
      message:
        type: string
        description: 추가 메시지
    example:
      code: '200'
      result: '[PVnT8fC73qOZuvVi, PVnT8fC73qOZuvVi, ...]'
      message: ''
  licence_photo_result:
    properties:
      code:
        type: integer
        description: 응답코드
      result:
        type: object
        $ref: "#/definitions/licenceData"
      message:
        type: string
        description: 추가 메시지
    example:
      code: '200'
      message: ''
      result:
        dateOfBirth: '11'
        areaCode: '700101'
        licenceNumber: '11-111111-11'
        issueDate: '2010-01-01'
        type: 'type1-common'
        imageUrl: 'yWQ5P97pkJw3Uqri'
  licenceData:
    properties:
      dateOfBirth:
        type: string
        description: 생년월일
      areaCode:
        type: string
        description: 지역코드
      licenceNumber:
        type: string
        description: 면허증 번호
      issueDate:
        type: string
        description: 발급 일자
      type:
        type: string
        description: '면허 유형 (2종보통 : type2-common, 1종보통 : type1-common,  1종대형 : type1-large)'
      imageUrl:
        type: string
        description: 이미지 아이디
  licence_photo_result_500:
    properties:
      code:
        type: string
        description: 응답코드
      result:
        type: string
        description: 등록된 파일의 실제 파일명
        example: 'reservation2021-01 driving distance.csv'
      message:
        type: string
        description: 추가 메시지
    example:
      code: '500'
      message: ''
      result: ''
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
